name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
       
        env: 
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: root
          
        ports:
          - 5432:5432
      

    steps:
    - uses: actions/checkout@v3

    - name: build makefile 
      run: make .PHONY

